steps:
  - label: ':pipeline: Create pipeline with priority'
    command: |
      if [[ "$${BUILDKITE_BRANCH}" == "$${BUILDKITE_PIPELINE_DEFAULT_BRANCH}" ]]; then
        export PRIORITY=1
      else
        export PRIORITY=0
      fi
      buildkite-agent pipeline upload <<YAML
      steps:
      - command: .buildkite/scripts/steps/bazel_cache/bootstrap_mac.sh
        label: Bootstrap (MacOS x86)
        priority: $${PRIORITY}
        agents:
          queue: macos-intel
        timeout_in_minutes: 60
      YAML
